sonar.projectKey=ordexxa_ordexxa-frontend
sonar.organization=ordexxa
sonar.projectName=Ordexxa Frontend
sonar.projectVersion=0.0.2-sonar

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**

# El frontend no tiene reporte de cobertura en esta fase; se mantiene análisis estático.
sonar.coverage.exclusions=**/*

sonar.sourceEncoding=UTF-8
